In [2]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

pd.set_option("display.max_columns", None)

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / "data" / "raw"

print("Project root:", PROJECT_ROOT)
print("Data directory:", DATA_DIR)

Project root: /Users/charlenephua/Library/Mobile Documents/com~apple~CloudDocs/uni/Y4/y4s1/bt4012/bt4012-fraud-detection
Data directory: /Users/charlenephua/Library/Mobile Documents/com~apple~CloudDocs/uni/Y4/y4s1/bt4012/bt4012-fraud-detection/data/raw

In [3]:
train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test.csv")
edges = pd.read_csv(DATA_DIR / "txs_edgelist.csv")
sample_submission = pd.read_csv(DATA_DIR / "sample_submission.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)
print("Edges shape:", edges.shape)
print("Submission shape:", sample_submission.shape)

Train shape: (141772, 168)
Test shape: (15329, 168)
Edges shape: (234355, 2)
Submission shape: (15329, 2)

In [4]:
display(train.head())
display(test.head())
display(edges.head())
display(sample_submission.head())

,txId,time_step,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,feat_11,feat_12,feat_13,feat_14,feat_15,feat_16,feat_17,feat_18,feat_19,feat_20,feat_21,feat_22,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,feat_32,feat_33,feat_34,feat_35,feat_36,feat_37,feat_38,feat_39,feat_40,feat_41,feat_42,feat_43,feat_44,feat_45,feat_46,feat_47,feat_48,feat_49,feat_50,feat_51,feat_52,feat_53,feat_54,feat_55,feat_56,feat_57,feat_58,feat_59,feat_60,feat_61,feat_62,feat_63,feat_64,feat_65,feat_66,feat_67,feat_68,feat_69,feat_70,feat_71,feat_72,feat_73,feat_74,feat_75,feat_76,feat_77,feat_78,feat_79,feat_80,feat_81,feat_82,feat_83,feat_84,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93,feat_94,feat_95,feat_96,feat_97,feat_98,feat_99,feat_100,feat_101,feat_102,feat_103,feat_104,feat_105,feat_106,feat_107,feat_108,feat_109,feat_110,feat_111,feat_112,feat_113,feat_114,feat_115,feat_116,feat_117,feat_118,feat_119,feat_120,feat_121,feat_122,feat_123,feat_124,feat_125,feat_126,feat_127,feat_128,feat_129,feat_130,feat_131,feat_132,feat_133,feat_134,feat_135,feat_136,feat_137,feat_138,feat_139,feat_140,feat_141,feat_142,feat_143,feat_144,feat_145,feat_146,feat_147,feat_148,feat_149,feat_150,feat_151,feat_152,feat_153,feat_154,feat_155,feat_156,feat_157,feat_158,feat_159,feat_160,feat_161,feat_162,feat_163,feat_164,feat_165,label
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,-0.167933,-0.049707,-0.164402,-0.028741,-0.035391,-0.042955,-0.013282,-0.057195,-0.169609,-0.171154,-0.174473,-1.373657,-1.371460,-0.139731,-0.148912,-0.080147,-0.155661,-0.010763,-0.012107,-0.139733,-0.148907,-0.080147,-0.155661,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.239368,-0.075256,-0.234952,0.037468,0.043444,-0.227203,-0.243236,-0.097895,-0.235896,0.036577,0.042345,-0.414005,-0.488340,-0.232553,-0.467554,0.048767,0.052956,-0.039149,-0.172895,-0.163126,-0.160932,-1.316342,-1.315388,-0.039144,-0.172884,-0.163115,-0.160925,-1.316333,-1.315375,-0.017032,-0.030026,-0.017640,-0.015071,-0.140763,-0.140335,-0.095403,-0.264376,-0.250523,-0.263703,1.133527,1.135947,-0.059013,-0.262368,-0.255111,-0.259194,1.125590,1.128038,-0.293773,-0.159732,0.034039,-0.183816,1.135523,1.135279,-0.169160,-0.201584,-0.116817,-0.191472,-0.014659,-0.018849,-1.457953,-1.494057,-0.083459,-1.485972,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.026060,-0.027660,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.120950,-0.199145,-0.187993,-0.212948,1.064205,1.063787,-1.373782,-1.354735,-0.297975,-1.403698,1.342003,1.340733,-0.171601,-0.458162,-0.423588,-0.440883,-1.015963,-1.016230,-0.968903,-0.375715,0.759748,-0.768329,1.488113,1.487932,-0.216814,-0.605631,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,NaN
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,-0.167948,-0.049707,-0.164417,-0.028741,-0.035391,-0.042955,-0.013282,-0.055327,-0.169757,-0.171477,-0.174490,0.887058,0.884557,-0.139731,-0.148912,-0.080147,-0.155661,-0.010763,-0.012107,-0.139733,-0.148907,-0.080147,-0.155661,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.239368,-0.075256,-0.234952,0.037468,0.043444,-0.227203,-0.243236,-0.097895,-0.235896,0.036577,0.042345,-0.413965,-0.488307,-0.232553,-0.467516,0.048767,0.052956,-0.039151,-0.172895,-0.163126,-0.160933,0.923473,0.923011,-0.039146,-0.172884,-0.163114,-0.160926,0.923516,0.923110,-0.017032,-0.030026,-0.017640,-0.015071,-0.140763,-0.140335,-0.095403,-0.264425,-0.250574,-0.263753,-0.169119,-0.167165,-0.059013,-0.262424,-0.255168,-0.259251,-0.187191,-0.185274,-0.293692,-0.760700,-0.692777,-0.719789,-1.084907,-1.084845,-0.170113,-0.202332,-0.116817,-0.192405,-0.014659,-0.018849,-1.457921,-1.494024,-0.083459,-1.485939,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.026060,-0.027660,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.121330,-0.110933,-0.075909,-0.111641,-1.159649,-1.160129,-1.373723,-1.353918,-0.295982,-1.403215,-0.975738,-0.975237,-0.168742,-0.263290,-0.186389,-0.250875,-1.015963,-1.016230,-0.968903,0.146997,1.366287,-0.464773,-1.116918,-1.116948,-0.216814,0.634272,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792,NaN
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,-0.168576,-0.049707,-0.165054,-0.028741,-0.035391,-0.042955,-0.013282,-0.055298,-0.170400,-0.172217,-0.175227,0.887058,0.884557,-0.139729,-0.148911,-0.080147,-0.155660,-0.010763,-0.012107,-0.139731,-0.148906,-0.080147,-0.155660,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227178,-0.239333,-0.075256,-0.234914,0.037468,0.043444,-0.227164,-0.243198,-0.097895,-0.235857,0.036577,0.042345,-0.268737,-0.367521,-0.232553,-0.328163,0.048767,0.052956,-0.039141,-0.172871,-0.163101,-0.160907,-1.316342,-1.315388,-0.039136,-0.172859,-0.163090,-0.160900,-1.316333,-1.315375,-0.017032,-0.030025,-0.017639,-0.015070,-2.428426,-2.429065,-0.095104,-0.263675,-0.249836,-0.262963,-1.471764,-1.470277,-0.058524,-0.261612,-0.254373,-0.258387,-1.499972,-1.498585,-0.021809,1.936814,2.448785,1.775108,-1.084907,-1.084845,-0.170528,-0.202658,-0.116817,-0.192811,-0.014659,-0.018849,-1.457953,-1.494057,-0.083459,-1.485972,-0.088798,-0.090437,-0.166550,-0.216536,-0.134546,-0.194817,-0.003175,-0.004094,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.026060,-0.027660,-0.095559,-0.145126,-0.097719,-0.129496,0.003143,0.002426,-0.122974,-0.041556,0.012549,-0.032244,-1.159649,-1.160129,-1.373902,-1.356210,-0.301548,-1.404577,-0.975738,-0.975237,-0.168742,-0.192468,-0.099790,-0.182133,-1.015963,-1.016230,-0.968903,-1.421138,-0.453330,-1.375441,-1.116918,-1.116948,-0.216814,0.407161,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792,NaN
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,-0.115831,0.043598,-0.163905,1.059993,2.397457,-0.063200,-0.013282,4.800240,0.174329,-0.172908,0.619399,-0.243300,-0.243452,-0.139732,-0.146895,-0.079667,-0.155554,0.773847,0.378516,-0.139734,-0.146891,-0.079667,-0.155553,0.773932,0.378593,-0.024669,-0.031271,-0.023044,-0.026215,0.101008,0.026315,-0.227215,-0.156772,0.089307,-0.212195,-2.772015,-2.371969,-0.227203,-0.221151,-0.066858,-0.232011,-2.165534,-2.175855,-0.414008,4.181192,4.346640,1.777963,-1.451545,-1.530250,4.628683,0.513804,-0.163126,1.208220,-0.196435,-0.196189,4.629650,0.513869,-0.163115,1.208278,-0.196409,-0.196133,-0.017032,-0.030026,-0.017640,-0.015071,-0.140763,-0.140335,4.313295,0.216750,-0.250574,0.707151,-0.169119,-0.167165,6.220011,0.216948,-0.255168,0.717108,-0.187191,-0.185274,3.991587,0.810879,-0.694235,2.084651,0.025308,0.025217,-0.171098,0.266450,0.159432,-0.159946,0.970465,1.928382,-1.457953,-1.493992,-0.083124,-1.485957,-0.234171,-0.205513,-0.176219,-0.056011,-0.082822,-0.191696,0.323773,0.668621,-1.096336,0.787435,0.856163,-1.104530,0.715115,0.958373,-0.116425,0.312047,0.064623,-0.101755,-0.247676,-1.201993,-0.095559,0.523326,0.019771,-0.119195,0.147881,0.956170,0.759756,-0.041556,-0.188716,0.149949,-0.047722,-0.048171,-1.373723,-1.356131,-0.301754,-1.404445,0.183133,0.182748,-0.163577,-0.456561,-0.424672,-0.436915,0.143001,0.142525,-0.425896,-1.421138,-1.059868,-1.071885,0.185597,0.185492,-0.216814,-0.617907,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792,0.0
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,0.041399,0.935886,-0.098695,1.203038,0.988902,0.341693,-0.013282,-0.057392,0.058329,-0.032930,-0.042709,0.065455,0.324947,-0.139732,-0.148854,-0.080105,-0.155638,1.313051,1.106965,-0.139734,-0.148850,-0.080104,-0.155638,1.313130,1.106995,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.239359,-0.075242,-0.234950,-0.866062,-0.856034,-0.227203,-0.243226,-0.097872,-0.235895,-0.871028,-0.861079,-0.414031,-0.487284,-0.231224,-0.467274,0.557030,0.745976,-0.039151,-0.172839,-0.163094,-0.160904,0.094039,0.222421,-0.039146,-0.172828,-0.163083,-0.160897,0.094081,0.202143,-0.017032,-0.029992,-0.017629,-0.015067,-0.309718,-0.309369,-0.095403,-0.264416,-0.250569,-0.263750,-0.842439,-0.840727,-0.059135,-0.262415,-0.255162,-0.259249,-0.696206,-0.714093,-0.293897,-0.761399,-0.693922,-0.720790,-0.487315,-0.563089,-0.162974,0.844932,1.723414,0.440298,1.214440,1.049649,-1.460035,-1.494122,-0.070389,-1.486470,-0.861325,-1.091559,-0.166550,-0.174293,-0.091258,-0.154707,1.664843,1.664621,-1.096336,-1.267340,-0.349933,-1.230441,-0.004358,-0.004194,-0.011925,1.228292,1.193497,1.471777,1.796374,1.817237,-0.093145,-0.116742,-0.077909,-0.093120,1.587690,1.586539,-0.101820,0.704558,0.448898,0.659662,0.311091,0.302198,-1.373962,-1.355393,-0.300941,-1.404583,0.064846,-0.035232,-0.168742,-0.442156,-0.416540,-0.418273,0.367605,0.392035,-0.968903,-1.943850,-1.059868,-1.678997,0.185597,0.185492,-0.169472,-0.470592,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117,NaN

,index,txId,time_step,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,feat_11,feat_12,feat_13,feat_14,feat_15,feat_16,feat_17,feat_18,feat_19,feat_20,feat_21,feat_22,feat_23,feat_24,feat_25,feat_26,feat_27,feat_28,feat_29,feat_30,feat_31,feat_32,feat_33,feat_34,feat_35,feat_36,feat_37,feat_38,feat_39,feat_40,feat_41,feat_42,feat_43,feat_44,feat_45,feat_46,feat_47,feat_48,feat_49,feat_50,feat_51,feat_52,feat_53,feat_54,feat_55,feat_56,feat_57,feat_58,feat_59,feat_60,feat_61,feat_62,feat_63,feat_64,feat_65,feat_66,feat_67,feat_68,feat_69,feat_70,feat_71,feat_72,feat_73,feat_74,feat_75,feat_76,feat_77,feat_78,feat_79,feat_80,feat_81,feat_82,feat_83,feat_84,feat_85,feat_86,feat_87,feat_88,feat_89,feat_90,feat_91,feat_92,feat_93,feat_94,feat_95,feat_96,feat_97,feat_98,feat_99,feat_100,feat_101,feat_102,feat_103,feat_104,feat_105,feat_106,feat_107,feat_108,feat_109,feat_110,feat_111,feat_112,feat_113,feat_114,feat_115,feat_116,feat_117,feat_118,feat_119,feat_120,feat_121,feat_122,feat_123,feat_124,feat_125,feat_126,feat_127,feat_128,feat_129,feat_130,feat_131,feat_132,feat_133,feat_134,feat_135,feat_136,feat_137,feat_138,feat_139,feat_140,feat_141,feat_142,feat_143,feat_144,feat_145,feat_146,feat_147,feat_148,feat_149,feat_150,feat_151,feat_152,feat_153,feat_154,feat_155,feat_156,feat_157,feat_158,feat_159,feat_160,feat_161,feat_162,feat_163,feat_164,feat_165
0,0,200459281,36,-0.172879,-0.058452,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,-0.163536,-0.169352,-0.049707,-0.165839,-0.028741,-0.035391,-0.042955,-0.013282,-0.057065,-0.171067,-0.172840,-0.176141,0.887058,0.884557,-0.132105,-0.144045,-0.080147,-0.149199,-0.010763,-0.012107,-0.132105,-0.144040,-0.080147,-0.149198,-0.010669,-0.012005,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.211084,-0.224180,-0.075256,-0.219162,0.037468,0.043444,-0.211222,-0.227604,-0.097895,-0.220010,0.036577,0.042345,1.041317,0.722046,-0.232553,0.928888,0.048767,0.052956,-0.039151,-0.172895,-0.163126,-0.160933,0.923473,0.923011,-0.039146,-0.172884,-0.163115,-0.160926,0.923516,0.923110,-0.017032,-0.030026,-0.01764,-0.015071,-0.140763,-0.140335,-0.095403,-0.264425,-0.250574,-0.263753,-0.169119,-0.167165,-0.059013,-0.262424,-0.255168,-0.259251,-0.187191,-0.185274,-0.293853,-0.761944,-0.694210,-0.720952,1.135523,1.135279,-0.170634,-0.202741,-0.116817,-0.192915,-0.014659,-0.018849,0.801938,0.803958,-0.083459,0.805795,-0.088798,-0.090437,-0.088200,-0.156977,-0.134546,-0.119971,-0.003175,-0.004094,1.023860,0.787435,-0.349933,0.939106,-0.004358,-0.004194,-0.116425,-0.176617,-0.137323,-0.152464,-0.026060,-0.027660,-0.093145,-0.143707,-0.097719,-0.127462,0.003143,0.002426,-0.124290,-0.193567,-0.180149,-0.207226,1.064205,1.063787,0.739947,0.502358,-0.301617,0.663148,1.342003,1.340733,0.398289,4.421702,5.327376,4.467085,1.301966,1.301281,0.117111,0.669709,0.759748,0.445895,1.488113,1.487932,0.090912,1.794379,2.262621,1.947206,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
1,1,199944769,36,-0.172828,0.339970,1.018602,0.178180,-0.043875,0.222447,-0.061584,-0.163620,-0.169419,-0.049636,-0.165915,-0.684027,-0.280462,-0.042955,-0.013282,-0.057112,-0.171012,-0.172773,-0.176081,0.887058,0.884557,-0.139732,-0.148899,-0.080135,-0.155656,-1.256340,-1.350850,-0.139734,-0.148895,-0.080135,-0.155656,-1.256230,-1.350662,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.229204,-0.054534,-0.232386,-2.497500,-2.278049,-0.227203,-0.234577,-0.071096,-0.233661,-2.454328,-2.289334,-0.414017,1.293405,2.274018,0.412020,-2.195071,-2.314499,-0.039151,-0.172895,-0.163125,-0.160932,0.923473,0.923011,-0.039146,-0.172884,-0.163114,-0.160925,0.923516,0.923110,-0.017032,-0.030026,-0.01764,-0.015071,-0.140763,-0.140335,-0.095403,-0.264229,-0.250372,-0.263555,1.133527,1.135947,-0.059013,-0.262340,-0.255082,-0.259166,1.125590,1.128038,-0.293836,0.012863,0.242795,-0.029899,1.135523,1.135279,-0.171000,-0.196295,-0.105635,-0.191358,-1.851472,-1.589295,0.801906,0.803926,-0.083459,0.805762,-0.088798,-0.090437,-0.112357,0.068929,0.249914,0.041779,-2.167565,-2.488271,0.493811,1.301128,1.146424,1.047583,-1.392015,-1.164644,-0.116425,-0.054451,0.041752,-0.016932,-1.193303,-0.766277,-0.093145,-0.115322,-0.071387,-0.113635,-2.997930,-2.856265,-0.124456,-0.200288,-0.188645,-0.214985,1.064205,1.063787,0.739917,0.648043,0.078507,0.744173,1.342003,1.340733,-0.127428,-0.319374,-0.270623,-0.292883,-1.015963,-1.016230,-0.968903,0.146997,1.366287,-0.464773,-1.116918,-1.116948,-0.145801,-0.556526,-0.524789,-0.531617,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,2,198827545,36,-0.172282,0.837998,1.018602,0.553368,-0.043875,0.641758,-0.061584,-0.163574,-0.169384,-0.049683,-0.165875,-0.537017,-0.644356,-0.042955,-0.013282,-0.056915,-0.170464,-0.172160,-0.175435,0.887058,0.884557,-0.139732,-0.148891,-0.080132,-0.155656,0.858847,0.036574,-0.139734,-0.148886,-0.080131,-0.155656,0.858931,0.036673,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.231734,-0.061432,-0.233140,1.162149,0.019063,-0.227203,-0.235078,-0.075332,-0.233996,1.160861,0.017857,-0.413909,1.483946,2.229657,0.132175,0.346156,-0.226761,-0.039151,-0.172894,-0.163124,-0.160931,0.923473,0.923011,-0.039146,-0.172883,-0.163113,-0.160924,0.923516,0.923110,-0.017032,-0.030026,-0.01764,-0.015071,-0.140763,-0.140335,-0.095403,-0.264359,-0.250506,-0.263687,1.133527,1.135947,-0.059013,-0.262359,-0.255101,-0.259185,1.125590,1.128038,-0.293864,-0.607805,-0.507798,-0.583480,1.135523,1.135279,-0.170705,-0.156941,-0.024920,-0.164119,-0.649499,-0.794034,0.801810,0.803828,-0.083459,0.805665,-0.088798,-0.090437,-0.112357,0.019284,0.046454,-0.063742,-1.390664,-0.845483,0.493811,0.787435,0.404160,0.505197,-0.323912,-0.323598,-0.116425,0.189881,0.240202,-0.055655,-0.861370,0.108187,-0.093145,0.067757,0.155473,0.024029,-0.941310,-0.941768,-0.122218,0.363919,0.527179,0.433935,1.064205,1.063787,0.739827,0.503464,-0.298456,0.663704,1.342003,1.340733,0.597008,1.496354,1.675046,1.687444,1.301966,1.301281,0.660117,1.192421,0.759748,1.053007,1.488113,1.487932,0.209268,0.910488,1.149152,1.070472,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
3,3,200997190,36,-0.172926,0.156148,1.573595,-0.046932,-0.043875,-0.029140,-0.061584,-0.163636,-0.169404,-0.049276,-0.165916,2.459222,2.415325,-0.042955,-0.013282,-0.057037,-0.171118,-0.172901,-0.176197,-1.373657,-1.371460,-0.139731,-0.148906,-0.080139,-0.155658,-2.700912,-2.689592,-0.139733,-0.148901,-0.080138,-0.155658,-2.700785,-2.689318,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.226572,-0.236696,-0.068346,-0.233248,-3.750710,-3.727742,-0.226553,-0.240732,-0.088377,-0.234301,-3.768682,-3.745387,-0.113792,1.367657,3.482625,0.747126,-2.841929,-2.831431,-0.039151,-0.172895,-0.163126,-0.160933,-1.316342,-1.315388,-0.039146,-0.172884,-0.163115,-0.160926,-1.316333,-1.315375,-0.017032,-0.030026,-0.01764,-0.015071,-0.140763,-0.140335,-0.095403,-0.264425,-0.250574,-0.263753,-0.169119,-0.167165,-0.059013,-0.262424,-0.255168,-0.259251,-0.187191,-0.185274,-0.293815,-0.761916,-0.694194,-0.720914,1.135523,1.135279,-0.170984,-0.186647,-0.072362,-0.183056,2.536784,2.532288,0.801970,0.803991,-0.083459,0.805827,-0.088798,-0.090437,0.105527,-0.007175,-0.128153,0.066684,3.018428,3.022501,0.493811,1.301128,2.179372,0.939106,3.667039,3.665469,-0.011925,-0.054451,0.004249,-0.007251,-3.327524,-3.330855,-0.054512,-0.118161,-0.093159,-0.092894,-3.872194,-3.871849,-0.120719,-0.185483,-0.170700,-0.197198,1.064205,1.063787,0.740036,0.502437,-0.301617,0.663235,1.342003,1.340733,0.428302,0.695589,0.759831,0.859448,1.301966,1.301281,1.203124,0.669709,-0.453330,1.053007,-1.116918,-1.116948,-0.027444,0.008182,0.125358,0.080204,1.461330,1.461369,0.018279,-0.049041,-0.038193,-0.011377,-1.760926,-1.760984
4,4,200996856,36,-0.171396,1.311640,1.573595,0.478330,-0.004174,0.474034,-0.061584,-0.163614,-0.168429,-0.045501,-0.165765,1.366023,1.698043,-0.002466,-0.013282,-0.056945,-0.170313,-0.172264,-0.175325,-0.004769,0.207752,-0.139732,-0.148911,-0.080146,-0.155662,-0.251487,0.480823,-0.139734,-0.148906,-0.080146,-0.155661,-0.251390,0.480894,-0.024669,-0.031272,-0.023045,-0.026215,0.001428,0.001483,-0.227215,-0.238451,-0.073864,-0.234741,-0.910049,-0.855425,-0.227203,-0.242302,-0.095727,-0.235685,-0.919650,-0.676445,-0.413988,-0.222581,0.147671,-0.292487,-0.214474,-0.634543,-0.039151,-0.172895,-0.163126,-0.160933,-0.311076,-0.420029,-0.039146,-0.172884,-0.163114,-0.160926,-0.311051,-0.419981,-0.017032,-0.030026,-0.01764,-0.015071,-0.140763,-0.140335,-0.095403,-0.264351,-0.250520,-0.263716,-1.178144,-1.176552,-0.059013,-0.262377,-0.255134,-0.259227,-1.204066,-1.202560,-0.293804,-0.604659,-0.560009,-0.650363,-0.833506,-0.418808,-0.171062,-0.184055,-0.092797,-0.189887,0.310630,1.384277,0.802002,0.804024,-0.083459,0.805860,-0.088798,-0.090437,-0.110979,-0.105296,-0.052241,-0.126536,-1.090017,-0.243836,-1.096336,1.301128,3.559369,-0.446993,-0.311018,-0.442803,-0.116425,-0.115534,-0.070586,-0.141708,-1.834346,-1.836894,-0.093145,-0.142288,-0.096644,-0.127236,2.125753,2.124454,-0.123239,-0.185483,-0.176118,-0.205014,-0.279910,0.174221,0.740096,0.504623,-0.298280,0.664290,-0.469725,-0.280446,-0.151059,0.695589,0.430188,0.421323,0.161989,0.606027,0.660117,0.669709,-0.238611,0.901229,1.415015,1.421096,-0.216814,0.008182,-0.106650,-0.137402,0.258822,0.729391,0.018279,0.393121,0.680158,0.462432,0.359796,1.091185

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206

   index  target
0      0     0.5
1      1     0.5
2      2     0.5
3      3     0.5
4      4     0.5